// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD2abfZbL_5vCsb07IQG7kXUC6UWDWlGk',
    appId: '1:1045473339587:web:3b279decc13dd7911dda76',
    messagingSenderId: '1045473339587',
    projectId: 'my-flutter-project-3ce10',
    authDomain: 'my-flutter-project-3ce10.firebaseapp.com',
    storageBucket: 'my-flutter-project-3ce10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcIeBf83jIGYE_yPkErOL8sPK6LiCWLiI',
    appId: '1:1045473339587:android:5126e12aaa9c91081dda76',
    messagingSenderId: '1045473339587',
    projectId: 'my-flutter-project-3ce10',
    storageBucket: 'my-flutter-project-3ce10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdQerCNMXe-VNZymawJMkWLRp8_tZl77M',
    appId: '1:1045473339587:ios:06cf9ccf390d208d1dda76',
    messagingSenderId: '1045473339587',
    projectId: 'my-flutter-project-3ce10',
    storageBucket: 'my-flutter-project-3ce10.appspot.com',
    iosBundleId: 'com.example.ebookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdQerCNMXe-VNZymawJMkWLRp8_tZl77M',
    appId: '1:1045473339587:ios:4e9eacb118accfd61dda76',
    messagingSenderId: '1045473339587',
    projectId: 'my-flutter-project-3ce10',
    storageBucket: 'my-flutter-project-3ce10.appspot.com',
    iosBundleId: 'com.example.ebookApp.RunnerTests',
  );
}
